config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'registration', to: 'users#new', as: 'registration'

  resources :sessions
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :samples

  resources :juice_shipments

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/addition.rb
class Addition < ApplicationRecord
  belongs_to :sample, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :test
  belongs_to :sample, optional: true
end

app/models/experiment.rb
class Experiment < ApplicationRecord
  belongs_to :test
  belongs_to :sample, optional: true
end

app/models/juice_shipment.rb
class JuiceShipment < ApplicationRecord
  has_many :samples
end

app/models/sample.rb
class Sample < ApplicationRecord
  belongs_to :juice_shipment
  belongs_to :stage
  has_many :additions
  has_many :experiments
end

app/models/stage.rb
class Stage < ApplicationRecord
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_user!
    redirect_to login_path unless current_user
  end

  def login(user)
    session[:user_id] = user.id
  end

  def logout
    session[:user_id] = nil
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/juice_shipments_controller.rb
class JuiceShipmentsController < ApplicationController
  def index
    @shipments = JuiceShipment.all.order(:date_received)
  end

  def new
    @juice_shipment = JuiceShipment.new
  end

  def create
    @juice_shipment = JuiceShipment.new(juice_shipment_params)
    if @juice_shipment.save
      redirect_to juice_shipments_path
    else
      render :new
    end
  end

  private

  def juice_shipment_params
    params.require(:juice_shipment).permit(:date_received, :apple_composition, :specific_gravity)
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :authenticate_user!

  def index
    @samples = Sample.all.order(:id)
  end

  def new
    @sample = Sample.new
  end

  def create
    @sample = Sample.new(sample_params)
    if @sample.save
      redirect_to samples_path
    else
      render :new
    end
  end

  def show
    @sample = Sample.find(params[:id])
  end

  private

  def sample_params
    params.require(:sample).permit(:start_date, :tote_size, :yeast_type, :round, :juice_shipment_id, :stage_id, :group)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    user = User.find_by(email: params[:email])
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      login(user)
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now.alert = 'Email or password is invalid'
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, notice: 'Logged out!'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Thank you for registering!'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/juice_shipments_helper.rb
module JuiceShipmentsHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
  def format_last_modified(sample)
    year = sample.updated_at.year
    month = sample.updated_at.month
    day = sample.updated_at.day
    hour = sample.updated_at.hour
    min = sample.updated_at.min
    sec = sample.updated_at.sec
    Time.zone.parse("#{year}-#{month}-#{day} #{hour}:#{min}:#{sec} +0000").strftime("%m-%d-%Y at %I:%M%p")
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<header>
  <%= render 'shared/nav'%>
</header>

<main role="main" class="home-page">
  <section class="jumbotron text-center">
    <!-- <div class="overlay">
    </div> -->
    <div class="container">
      <h1 class="app-intro-text app-intro-text-lg">Core.io</h1>
      <p class="app-intro-text">A tool for the collection, management, and analysis of cellar data</p>
    </div>
  </section>

  <section class="app-features">
    <div class="container">
      <h1 class="text-center">Explore Core.io</h1>
      <div class="row">
        <div class="col-xs-12 col-md-4 mt-2">
          <div class="app-feature d-flex flex-column align-tems-center justify-content-center">
            <%= fa_icon "edit 2x", class: "app-options-icon text-center" %>
            <h2 class="app-options-header text-center">Record Data</h2>
            <p class="app-options-desc text-center">Record keeping made simple with Core. Manage samples, add experiemental results, and track chemical additions. </p>
            <div class="mx-auto">
              <button class="btn btn-primary btn-sm action-button ">Learn More</button>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-md-4 mt-2">
          <div class="app-feature d-flex flex-column align-tems-center justify-content-center">
            <%= fa_icon "database 2x", class: "app-options-icon text-center"%>
            <h2 class="app-options-header text-center">Perform Analysis</h2>
            <p class="app-options-desc text-center">Quick visualization of fermentation data and chemical efficacy with live updated charts and diagrams.</p>
            <div class="mx-auto">
              <button class="btn btn-primary btn-sm action-button ">Learn More</button>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-md-4 mt-2">
          <div class="app-feature d-flex flex-column align-tems-center justify-content-center">
            <%= fa_icon "flask 2x", class: "app-options-icon text-center"%>
            <h2 class="app-options-header text-center">Schedule Experiments</h2>
            <p class="app-options-desc text-center">Use the calendar feature to schedule tasks and experiements so you never miss out on valuable data.</p>
            <div class="mx-auto">
              <button class="btn btn-primary btn-sm action-button ">Learn More</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>

app/views/juice_shipments/new.html.erb
<header>
  <%=render 'shared/nav'%>
</header>

<main role="main">
  <section class="new-shipment d-flex align-items-center">
    <div class="container w-75 mb-4">
      <h1 class="new-shipment-title text-center mt-4 mb-2">Add a Juice Shipment</h1>
      <div class="row justify-content-center">
        <div class="col">
          <%= form_for @juice_shipment, url: juice_shipments_path do |f| %>

            <div class="form-group">
              <%= f.label :date_received %><br />
              <%= f.date_select :date_received, class: "form-control"%>
            </div>

            <div class="form-group">
              <%= f.label :apple_composition %><br />
              <%= f.text_field :apple_composition, class: "form-control", 'aria-describedby': "appleCompHelp", placeholder:"Enter the apple composition" %>
              <small id="appleCompHelp" class="form-text text-muted">Enter the different types of apples present in the juice</small>
            </div>

            <div class="form-group">
              <%= f.label :specific_gravity %><br />
              <%= f.text_field :specific_gravity, class: "form-control", 'aria-describedby': "gravityHelp", placeholder:"Enter the specific gravity"%>
              <small id="gravityHelp" class="form-text text-muted">Enter the specific gravity as a decimal value</small>
            </div>

            <button type="submit" class="btn btn-primary action-button">Create Shipment</button>
          <% end %>
        </div>
      </div>
    </div>
  </section>
</main>

app/views/samples/index.html.erb
<header>
  <%= render 'shared/nav'%>
</header>

<main role="main">

  <section class="all-samples">
    <div class="container">
      <h1 class="text-center mt-4">Samples</h1>
      <h2 class="text-center text-muted">All active samples are listed below</h2>
      <div class="d-flex justify-content-center mt-2 mb-2 new-sample">
        <%= link_to "Create A New Sample", new_sample_path, class: "btn btn-primary action-button"%>
      </div>

        <div class="row mb-4">
          <%@samples.each do |sample|%>
            <div class="col-xs-12 col-md-3" style="min-width:15rem;">
              <div class="card mt-2 mb-2">
                <div class="card-body">
                  <h5 class="card-title">Sample #<%=sample.id%></h5>
                  <h6 class="card-subtitle mb-2 text-muted">Sample Group #<%=sample.group%></h6>
                  <p class="card-text">Stage:</br> <%=sample.stage.description.capitalize%></p>
                  <p class="card-text">Last Modified:</br> <%=format_last_modified(sample)%></p>
                  <%=link_to "More Details", sample_path(sample.id), class:"card-link action-link"%>
                </div>
              </div>
            </div>
          <%end%>
        </div>
    </div>
  </section>
</main>

app/views/samples/new.html.erb
<header>
  <%=render 'shared/nav'%>
</header>

<main role="main">
  <section class="new-sample d-flex align-items-center">
    <div class="container w-75 mb-4">
      <h1 class="new-sample-title text-center mt-4 mb-2">Add a Sample</h1>
      <p class="text-muted text-center"><span class="asterisk">**</span>Please note that a <%= link_to 'juice shipment', new_juice_shipment_path, class: "action-link"%> must exist before a sample can be created. </p>
      <div class="row justify-content-center">
        <div class="col">
          <%= form_for @sample, url: samples_path do |f| %>

            <div class="form-group">
              <%= f.label :start_date %><br />
              <%= f.date_select :start_date, class: "form-control"%>
            </div>

            <div class="form-group">
              <%= f.label :tote_size %><br />
              <%= f.text_field :tote_size, class: "form-control", 'aria-describedby': "toteSizeHelp", placeholder:"Enter tote size" %>
              <small id="toteSizeHelp" class="form-text text-muted">Enter tote size as an integer without units</small>
            </div>

            <div class="form-group">
              <%= f.label :group %><br />
              <%= f.text_field :group, class: "form-control", 'aria-describedby': "groupHelp", placeholder:"Enter sample group"%>
              <small id="groupHelp" class="form-text text-muted">Enter the group name in the format of 'SG-n'</small>
            </div>

            <div class="form-group">
              <%= f.label :yeast_type %><br />
              <%= f.text_field :yeast_type, class: "form-control", placeholder:"Enter yeast type used" %>
            </div>

            <div class="form-group">
              <%= f.label :pitch_round %><br />
              <%= f.text_field :round, class: "form-control", 'aria-describedby': "roundHelp", placeholder:"Enter the pitch round" %>
              <small id="roundHelp" class="form-text text-muted">Enter round as an integer representing how many times lees has been used</small>

            </div>

            <div class="form-group">
              <%= f.label :juice_shipment %><br />
              <%= f.select :juice_shipment_id, JuiceShipment.order(:date_received).collect { |j| [ j.date_received, j.id ] }, include_blank: true%>
            </div>

            <div class="form-group">
              <%= f.label :stage %><br />
              <%= f.select :stage_id, Stage.order(:description).collect { |s| [ s.description, s.id ] }, include_blank: true%>
            </div>

            <button type="submit" class="btn btn-primary action-button">Create Sample</button>
          <% end %>
        </div>
      </div>
    </div>
  </section>
</main>

app/views/samples/show.html.erb
<header>
  <%=render 'shared/nav'%>
</header>

<div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item mt-2">
                <a class="nav-link action-link" href="#">
                  Back to All <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link action-link" href="#">
                  Additions
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link action-link" href="#">
                  Experiments
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2 sample-id">Sample #<%=@sample.id%></h1>

            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <button class="btn btn-sm btn-outline-secondary">Share</button>
                <button class="btn btn-sm btn-outline-secondary">Export</button>
              </div>
            </div>
          </div>

          <div class="my-4 w-100 host-container">
            <div class="container">
              <div class="row justify-content-center">
                <div class="col-xs-12">
                  <div class="crud-row d-flex justify-content-between">
                    <div class="mr-2">
                      <%= button_to "Update", edit_sample_path(@sample), class: "btn btn-primary action-button"%>
                    </div>
                    <div class="ml-2">
                      <%= button_to "Delete", sample_path, class: "btn btn-primary action-button"%>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="container mt-4">
              <div class="row justify-content-center">
                <div class="col-xs-12">
                  <div class="card mt-2 mb-2" style="width:50vw">
                    <div class="card-body">
                      <h5 class="card-title">Group</h5>
                      <h6 class="card-subtitle mb-2 text-muted">Sample Group #<%=@sample.group%></h6>
                      <p class="card-text">Stage:</br> <%=@sample.stage.description.capitalize%></p>
                      <p class="card-text">Last Modified:</br> <%=format_last_modified(@sample)%></p>
                      <%=link_to "More Details", sample_path(@sample.id), class:"card-link action-link"%>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas> -->

          <h2>Additions</h2>
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Chemical Name</th>
                  <th>Amount</th>
                  <th>Date Added</th>
                  <th>Notes</th>
                </tr>
              </thead>
              <tbody>
                <%@sample.additions.each do |addition|%>
                  <tr>
                    <td>addition.id</td>
                    <td>addition.chemical_name</td>
                    <td>addition.amount</td>
                    <td>addition.date</td>
                    <td>addition.notes</td>
                  </tr>
                <%end%>
                <!-- <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>
                <tr>
                  <td>1,002</td>
                  <td>amet</td>
                  <td>consectetur</td>
                  <td>adipiscing</td>
                  <td>elit</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>Integer</td>
                  <td>nec</td>
                  <td>odio</td>
                  <td>Praesent</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>libero</td>
                  <td>Sed</td>
                  <td>cursus</td>
                  <td>ante</td>
                </tr>
                <tr>
                  <td>1,004</td>
                  <td>dapibus</td>
                  <td>diam</td>
                  <td>Sed</td>
                  <td>nisi</td>
                </tr>
                <tr>
                  <td>1,005</td>
                  <td>Nulla</td>
                  <td>quis</td>
                  <td>sem</td>
                  <td>at</td>
                </tr>
                <tr>
                  <td>1,006</td>
                  <td>nibh</td>
                  <td>elementum</td>
                  <td>imperdiet</td>
                  <td>Duis</td>
                </tr>
                <tr>
                  <td>1,007</td>
                  <td>sagittis</td>
                  <td>ipsum</td>
                  <td>Praesent</td>
                  <td>mauris</td>
                </tr>
                <tr>
                  <td>1,008</td>
                  <td>Fusce</td>
                  <td>nec</td>
                  <td>tellus</td>
                  <td>sed</td>
                </tr>
                <tr>
                  <td>1,009</td>
                  <td>augue</td>
                  <td>semper</td>
                  <td>porta</td>
                  <td>Mauris</td>
                </tr>
                <tr>
                  <td>1,010</td>
                  <td>massa</td>
                  <td>Vestibulum</td>
                  <td>lacinia</td>
                  <td>arcu</td>
                </tr>
                <tr>
                  <td>1,011</td>
                  <td>eget</td>
                  <td>nulla</td>
                  <td>Class</td>
                  <td>aptent</td>
                </tr>
                <tr>
                  <td>1,012</td>
                  <td>taciti</td>
                  <td>sociosqu</td>
                  <td>ad</td>
                  <td>litora</td>
                </tr>
                <tr>
                  <td>1,013</td>
                  <td>torquent</td>
                  <td>per</td>
                  <td>conubia</td>
                  <td>nostra</td>
                </tr>
                <tr>
                  <td>1,014</td>
                  <td>per</td>
                  <td>inceptos</td>
                  <td>himenaeos</td>
                  <td>Curabitur</td>
                </tr>
                <tr>
                  <td>1,015</td>
                  <td>sodales</td>
                  <td>ligula</td>
                  <td>in</td>
                  <td>libero</td>
                </tr> -->
              </tbody>
            </table>
          </div>
        </main>
      </div>
    </div>

app/views/users/new.html.erb
<header>
  <%=render 'shared/nav'%>
</header>

<main role="main">
  <section class="registration d-flex align-items-center">
    <div class="container w-50">
      <h1 class="registration-title text-center">Register</h1>
      <div class="row justify-content-center">
        <div class="col">
          <%= form_for @user, url: users_path do |f| %>

            <div class="form-group">
              <%= f.label :name %><br />
              <%= f.text_field :name, class: "form-control", placeholder: "Enter Your Name" %>
            </div>

            <div class="form-group">
              <%= f.label :email %><br />
              <%= f.text_field :email, class: "form-control", placeholder: "Enter Your Email" %>
            </div>

            <div class="form-group">
              <%= f.label :password %><br />
              <%= f.password_field :password, class: "form-control", placeholder: "Choose a password" %>
            </div>

            <div class="form-group">
              <%= f.label :password_confirmation %><br />
              <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm your password" %>
            </div>

            <button type="submit" class="btn btn-primary action-button">Register</button>
          <% end %>
        </div>
      </div>
    </div>
  </section>
</main>