config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'registration', to: 'users#new', as: 'registration'

  resources :sessions
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :samples

  resources :juice_shipments

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/addition.rb
class Addition < ApplicationRecord
  belongs_to :sample, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :test
  belongs_to :sample, optional: true
end

app/models/experiment.rb
class Experiment < ApplicationRecord
  belongs_to :test
  belongs_to :sample, optional: true
end

app/models/juice_shipment.rb
class JuiceShipment < ApplicationRecord
  has_many :samples
end

app/models/sample.rb
class Sample < ApplicationRecord
  belongs_to :juice_shipment
  belongs_to :stage
  has_many :additions
  has_many :experiments
end

app/models/stage.rb
class Stage < ApplicationRecord
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_user!
    redirect_to login_path unless current_user
  end

  def login(user)
    session[:user_id] = user.id
  end

  def logout
    session[:user_id] = nil
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :authenticate_user!

  def index
    @samples = Sample.all.order(:id)
  end

  def new
    @sample = Sample.new
  end

  def create
    @sample = Sample.new(sample_params)
    if @sample.save
      redirect_to samples_path
    else
      render :new
    end
  end

  def show
    @sample = Sample.find(params[:id])
  end

  private

  def sample_params
    params.require(:sample).permit(:start_date, :tote_size, :yeast_type, :round, :juice_shipment_id, :stage_id, :group)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    user = User.find_by(email: params[:email])
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      login(user)
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now.alert = 'Email or password is invalid'
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, notice: 'Logged out!'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Thank you for registering!'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/juice_shipments_helper.rb
module JuiceShipmentsHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
  def format_last_modified(sample)
    year = sample.updated_at.year
    month = sample.updated_at.month
    day = sample.updated_at.day
    hour = sample.updated_at.hour
    min = sample.updated_at.min
    sec = sample.updated_at.sec
    Time.zone.parse("#{year}-#{month}-#{day} #{hour}:#{min}:#{sec} +0000").strftime("%m-%d-%Y at %I:%M%p")
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fftt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<header>
  <%= render 'shared/nav'%>
</header>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-dark">
  <a class="navbar-brand" href="/"><%=image_tag "FFTT_ROUND_logo.png", class: "nav-logo"%></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav ml-auto">
      <a class="nav-item nav-link fftt-nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      <%= link_to 'View Data', samples_path, class: "nav-item nav-link fftt-nav-link" %>

      <!-- <a class="nav-item nav-link fftt-nav-link" href="#">View Data</a> -->
      <a class="nav-item nav-link fftt-nav-link" href="#">Record Data</a>
      <% if current_user %>
        <%= link_to 'Logout', logout_path, class: "nav-item nav-link fftt-nav-link" %>
      <% else %>
        <%= link_to "Register", registration_path, class: "nav-item nav-link fftt-nav-link" %>
        <%= link_to "Log In", login_path, class: "nav-item nav-link fftt-nav-link" %>
      <% end %>
    </div>
  </div>
</nav>